language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
  - echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install siegfried
  - sudo apt-get install clamav && sudo freshclam
  - sudo apt-get install tree
  - git clone git://github.com/sleuthkit/sleuthkit.git
  - cd sleuthkit && ./bootstrap && ./configure && make && sudo make install && sudo ldconfig
  - cd ..
install:
  - pip install requests
script:
  - python test.py

